name: å“è³ªæ¤œæŸ»
on:
  pull_request:
    branches:
      - main
jobs:
  check:
    name: å“è³ªæ¤œæŸ»
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ”¨ Checkout!
        uses: actions/checkout@v4
      - name: ğŸ”¨ Setup Bun
        uses: oven-sh/setup-bun@v1
      - name: ğŸ”¨ Install
        run: bun install --ignore-scripts        
      - name: ğŸ’ª Build
        run: bun prisma generate
      - name: ğŸ” Run TypeScript
        run: bun --cwd app tsc --noEmit
      - name: ğŸ¬ Run Test
        run: bun test
